{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"sickness_research_3.ipynb","provenance":[],"collapsed_sections":[],"toc_visible":true},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.4"},"accelerator":"GPU"},"cells":[{"cell_type":"code","metadata":{"id":"xaDLqTCgkwvr","colab_type":"code","colab":{"base_uri":"https://localhost:8080/","height":34},"outputId":"83cdd1d8-532c-4eab-8793-ebd174916f88","executionInfo":{"status":"ok","timestamp":1588016550675,"user_tz":420,"elapsed":990,"user":{"displayName":"Mark Christian Navalta","photoUrl":"","userId":"09219874191985009997"}}},"source":["!pip uninstall tensorflow -y\n","!pip install tensorflow==2.1"],"execution_count":1,"outputs":[{"output_type":"stream","text":["Successfully installed gast-0.2.2 tensorboard-2.1.1 tensorflow-2.1.0 tensorflow-estimator-2.1.0\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"colab_type":"code","executionInfo":{"status":"ok","timestamp":1588016585320,"user_tz":420,"elapsed":20887,"user":{"displayName":"Mark Christian Navalta","photoUrl":"","userId":"09219874191985009997"}},"id":"-E03kYy1_awS","outputId":"8c99b508-ae59-4a5f-d884-d58662d90110","colab":{"base_uri":"https://localhost:8080/","height":122}},"source":["%load_ext autoreload\n","%autoreload 2\n","\n","from google.colab import drive\n","drive.mount('/content/gdrive')"],"execution_count":2,"outputs":[{"output_type":"stream","text":["Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly\n","\n","Enter your authorization code:\n","··········\n","Mounted at /content/gdrive\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"G3PxpiO3AmcF","colab_type":"code","colab":{}},"source":["LOCAL_XRAY_LOCATION = \"/content/xray_code\"\n","\n","import os\n","import shutil\n","if not os.path.exists(LOCAL_XRAY_LOCATION):\n","    shutil.copytree(\"/content/gdrive/My Drive/xray_code/\",\n","                    LOCAL_XRAY_LOCATION)"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"colab_type":"code","id":"5a7g2a7K_awZ","outputId":"25b6eb1b-104e-4971-95e2-906cbfc6be4d","executionInfo":{"status":"ok","timestamp":1588017358809,"user_tz":420,"elapsed":277505,"user":{"displayName":"Mark Christian Navalta","photoUrl":"","userId":"09219874191985009997"}},"colab":{"base_uri":"https://localhost:8080/","height":1000}},"source":["\"\"\"\n","SICKNESS = \"Infiltration\"\n","SICKNESS = \"Pneumonia\"\n","SICKNESS = \"Mass\"\n","SICKNESS = \"Pneumothorax\"\n","\"\"\"\n","\n","SICKNESS = \"Pneumothorax\"\n","csv_file = \"normalized_xray_without_full_path.csv\"\n","csv_file_full_path = f'{LOCAL_XRAY_LOCATION}/sheet/{csv_file}'\n","\n","IMAGE_SIZE = 224\n","BATCH_SIZE = 32\n","EPOCH = 1000\n","\n","python_file = f\"{LOCAL_XRAY_LOCATION}/python_code/sickness_pipeline.py\"\n","\n","!export IMAGE_URL=https://xrayimages.nyc3.digitaloceanspaces.com/v0.1/\n","!python $python_file -img $IMAGE_SIZE -s $SICKNESS -b $BATCH_SIZE -f $csv_file_full_path -e $EPOCH"],"execution_count":6,"outputs":[{"output_type":"stream","text":["2020-04-27 19:51:25.588043: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2020-04-27 19:51:25.588178: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia\n","2020-04-27 19:51:25.588204: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.\n","/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.\n","  import pandas.util.testing as tm\n","==================================================\n","No Finding            60361\n","Infiltration          19894\n","Effusion              13317\n","Atelectasis           11559\n","Nodule                 6331\n","Mass                   5782\n","Pneumothorax           5302\n","Consolidation          4667\n","Pleural_Thickening     3385\n","Cardiomegaly           2776\n","Emphysema              2516\n","Edema                  2303\n","Fibrosis               1686\n","Pneumonia              1431\n","Hernia                  227\n","Name: labels, dtype: int64\n","==================================================\n","No Finding      5302\n","Pneumothorax    5302\n","Name: labels, dtype: int64\n","Pneumothorax    4242\n","No Finding      4241\n","Name: labels, dtype: int64\n","==================================================\n","No Finding      854\n","Pneumothorax    842\n","Name: labels, dtype: int64\n","==================================================\n","Pneumothorax    218\n","No Finding      207\n","Name: labels, dtype: int64\n","/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/dataframe_iterator.py:273: UserWarning: Found 8483 invalid image filename(s) in x_col=\"Image Index\". These filename(s) will be ignored.\n","  .format(n_invalid, x_col)\n","Found 0 validated image filenames belonging to 0 classes.\n","/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/dataframe_iterator.py:273: UserWarning: Found 1696 invalid image filename(s) in x_col=\"Image Index\". These filename(s) will be ignored.\n","  .format(n_invalid, x_col)\n","Found 0 validated image filenames belonging to 0 classes.\n","/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/dataframe_iterator.py:273: UserWarning: Found 425 invalid image filename(s) in x_col=\"Image Index\". These filename(s) will be ignored.\n","  .format(n_invalid, x_col)\n","Found 0 validated image filenames belonging to 0 classes.\n","==================================================\n","\n","Traceback (most recent call last):\n","  File \"/content/xray_code/python_code/sickness_pipeline.py\", line 217, in <module>\n","    pipeline.run()\n","  File \"/content/xray_code/python_code/sickness_pipeline.py\", line 178, in run\n","    self._main_process()\n","  File \"/content/xray_code/python_code/sickness_pipeline.py\", line 117, in _main_process\n","    self.Epoch, self.train_data, self.val_data)\n","  File \"/content/xray_code/python_code/ml_utils.py\", line 118, in train_model\n","    model = self.create_model()\n","  File \"/content/xray_code/python_code/ml_utils.py\", line 141, in create_model\n","    input_shape=(self.IMAGE_SIZE, self.IMAGE_SIZE, 3)),\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_hub/keras_layer.py\", line 146, in __init__\n","    self._func = load_module(handle, tags)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_hub/keras_layer.py\", line 398, in load_module\n","    return module_v2.load(handle, tags=tags)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_hub/module_v2.py\", line 97, in load\n","    module_path = resolve(handle)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_hub/module_v2.py\", line 53, in resolve\n","    return registry.resolver(handle)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_hub/registry.py\", line 42, in __call__\n","    return impl(*args, **kwargs)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_hub/compressed_module_resolver.py\", line 88, in __call__\n","    self._lock_file_timeout_sec())\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_hub/resolver.py\", line 405, in atomic_download\n","    _wait_for_lock_to_disappear(handle, lock_file, lock_file_timeout_sec)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_hub/resolver.py\", line 342, in _wait_for_lock_to_disappear\n","    time.sleep(5)\n","KeyboardInterrupt\n","^C\n"],"name":"stdout"}]},{"cell_type":"code","metadata":{"id":"lKZw0NnaIf_v","colab_type":"code","colab":{}},"source":[""],"execution_count":0,"outputs":[]}]}